# UI_files/mainWindow_ui.py
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Set overall style and palette (old color scheme)
        MainWindow.setStyleSheet("""
        QMainWindow {
            background-color: rgb(94, 134, 171);
        }
        """)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1321, 696)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, 
                                           QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 134, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(142, 201, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(118, 167, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 67, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 89, 114))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(94, 134, 171))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(174, 194, 213))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setWindowTitle("Germination Vigor Analyser")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)

        buttonStyle = ("font: 63 10pt 'Segoe UI Semibold'; color: rgb(32, 24, 255);"
                                              "background-color: rgba(216, 229, 253,255);"
                                              "border-radius:4; padding:6px;")
        
        # Central widget and main horizontal layout
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(10, 10, 10, 10)
        self.mainLayout.setSpacing(10)
        
        #### LEFT SIDE ####
        self.leftWidget = QtWidgets.QWidget(self.centralwidget)
        self.leftWidget.setObjectName("leftWidget")
        self.leftLayout = QtWidgets.QVBoxLayout(self.leftWidget)
        self.leftLayout.setContentsMargins(0, 0, 0, 0)
        self.leftLayout.setSpacing(10)
        
        # 1. Big image area (placeholder for PhotoViewer)
        self.imageArea = QtWidgets.QLabel(self.leftWidget)
        self.imageArea.setObjectName("imageArea")
        self.imageArea.setAlignment(QtCore.Qt.AlignCenter)
        self.imageArea.setText("Image / Drawing Area")
        self.imageArea.setMinimumSize(400, 400)
        self.leftLayout.addWidget(self.imageArea, stretch=3)
        
        # 2. Navigation controls
        self.navWidget = QtWidgets.QWidget(self.leftWidget)
        self.navWidget.setObjectName("navWidget")
        self.navLayout = QtWidgets.QHBoxLayout(self.navWidget)
        self.navLayout.setContentsMargins(0, 0, 0, 0)
        self.navLayout.setSpacing(10)
        self.btnPrev = QtWidgets.QPushButton("<", self.navWidget)
        self.btnPrev.setObjectName("btnPrev")
        self.btnPrev.setFixedSize(100, 30)
        self.label_img_no = QtWidgets.QLabel("0 / 0", self.navWidget)
        self.label_img_no.setObjectName("label_img_no")
        self.label_img_no.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_no.setFixedWidth(50)  # Adjust the width as needed
        self.btnNext = QtWidgets.QPushButton(">", self.navWidget)
        self.btnNext.setObjectName("btnNext")
        self.btnNext.setFixedSize(100, 30)
        self.navLayout.addWidget(self.btnPrev)
        self.navLayout.addWidget(self.label_img_no)
        self.navLayout.addWidget(self.btnNext)
        self.navLayout.setAlignment(QtCore.Qt.AlignCenter)
        self.leftLayout.addWidget(self.navWidget, stretch=0)
        
        # 3. Metrics grid
        self.metricsWidget = QtWidgets.QWidget(self.leftWidget)
        self.metricsWidget.setObjectName("metricsWidget")
        self.metricsLayout = QtWidgets.QGridLayout(self.metricsWidget)
        self.metricsLayout.setContentsMargins(0, 0, 0, 0)
        self.metricsLayout.setSpacing(10)

        # Group 1 headers - apply new stylesheet
        self.label_growth_header = QtWidgets.QLabel("Growth", self.metricsWidget)
        self.label_growth_header.setStyleSheet(buttonStyle)
        self.label_sd_header = QtWidgets.QLabel("Std. Deviation", self.metricsWidget)
        self.label_sd_header.setStyleSheet(buttonStyle)
        self.label_uniformity_header = QtWidgets.QLabel("Uniformity", self.metricsWidget)
        self.label_uniformity_header.setStyleSheet(buttonStyle)
        self.label_vigor_header = QtWidgets.QLabel("Vigor", self.metricsWidget)
        self.label_vigor_header.setStyleSheet(buttonStyle)

        self.metricsLayout.addWidget(self.label_growth_header, 0, 0)
        self.metricsLayout.addWidget(self.label_sd_header, 0, 1)
        self.metricsLayout.addWidget(self.label_uniformity_header, 0, 2)
        self.metricsLayout.addWidget(self.label_vigor_header, 0, 3)

        # Group 1 values
        self.label_growth_value = QtWidgets.QLabel("", self.metricsWidget)
        self.label_growth_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sd_value = QtWidgets.QLabel("", self.metricsWidget)
        self.label_sd_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_uniformity_value = QtWidgets.QLabel("", self.metricsWidget)
        self.label_uniformity_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vigor_value = QtWidgets.QLabel("", self.metricsWidget)
        self.label_vigor_value.setAlignment(QtCore.Qt.AlignCenter)
        self.metricsLayout.addWidget(self.label_growth_value, 1, 0)
        self.metricsLayout.addWidget(self.label_sd_value, 1, 1)
        self.metricsLayout.addWidget(self.label_uniformity_value, 1, 2)
        self.metricsLayout.addWidget(self.label_vigor_value, 1, 3)

        # Group 2 headers - apply new stylesheet
        self.label_germ_header = QtWidgets.QLabel("Germination", self.metricsWidget)
        self.label_germ_header.setStyleSheet(buttonStyle)
        self.label_avg_hypocotyl_header = QtWidgets.QLabel("Avg Hypocotyl (cm)", self.metricsWidget)
        self.label_avg_hypocotyl_header.setStyleSheet(buttonStyle)
        self.label_avg_root_header = QtWidgets.QLabel("Avg Root (cm)", self.metricsWidget)
        self.label_avg_root_header.setStyleSheet(buttonStyle)
        self.label_avg_total_header = QtWidgets.QLabel("Avg Total Length (cm)", self.metricsWidget)
        self.label_avg_total_header.setStyleSheet(buttonStyle)

        self.metricsLayout.addWidget(self.label_germ_header, 2, 0)
        self.metricsLayout.addWidget(self.label_avg_hypocotyl_header, 2, 1)
        self.metricsLayout.addWidget(self.label_avg_root_header, 2, 2)
        self.metricsLayout.addWidget(self.label_avg_total_header, 2, 3)

        # Group 2 values
        self.label_germ_value = QtWidgets.QLabel("", self.metricsWidget)
        self.label_germ_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_avg_hypocotyl_value = QtWidgets.QLabel("", self.metricsWidget)
        self.label_avg_hypocotyl_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_avg_root_value = QtWidgets.QLabel("", self.metricsWidget)
        self.label_avg_root_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_avg_total_value = QtWidgets.QLabel("", self.metricsWidget)
        self.label_avg_total_value.setAlignment(QtCore.Qt.AlignCenter)
        self.metricsLayout.addWidget(self.label_germ_value, 3, 0)
        self.metricsLayout.addWidget(self.label_avg_hypocotyl_value, 3, 1)
        self.metricsLayout.addWidget(self.label_avg_root_value, 3, 2)
        self.metricsLayout.addWidget(self.label_avg_total_value, 3, 3)

        self.leftLayout.addWidget(self.metricsWidget, stretch=1)
        
        self.mainLayout.addWidget(self.leftWidget, 2)
        
        #### RIGHT SIDE ####
        self.rightWidget = QtWidgets.QWidget(self.centralwidget)
        self.rightWidget.setObjectName("rightWidget")
        self.rightLayout = QtWidgets.QVBoxLayout(self.rightWidget)
        self.rightLayout.setSpacing(10)
        # InfoGroup on right
        self.infoGroup = QtWidgets.QGroupBox("Information", self.rightWidget)
        self.infoGroup.setObjectName("infoGroup")
        self.infoLayout = QtWidgets.QGridLayout(self.infoGroup)
        self.infoLayout.setSpacing(5)
        self.label_fileName_info = QtWidgets.QLabel("File Name:", self.infoGroup)
        self.label_fileName_info_value = QtWidgets.QLabel("", self.infoGroup)
        self.infoLayout.addWidget(self.label_fileName_info, 0, 0)
        self.infoLayout.addWidget(self.label_fileName_info_value, 0, 1)
        self.label_cult_info = QtWidgets.QLabel("Cultivar Name:", self.infoGroup)
        self.label_cult_name_info = QtWidgets.QLabel("", self.infoGroup)
        self.infoLayout.addWidget(self.label_cult_info, 1, 0)
        self.infoLayout.addWidget(self.label_cult_name_info, 1, 1)
        self.label_analyst_info = QtWidgets.QLabel("Analyst Name:", self.infoGroup)
        self.label_analys_name_info = QtWidgets.QLabel("", self.infoGroup)
        self.infoLayout.addWidget(self.label_analyst_info, 2, 0)
        self.infoLayout.addWidget(self.label_analys_name_info, 2, 1)
        self.label_lot_info = QtWidgets.QLabel("Lot No.:", self.infoGroup)
        self.label_batchNo_info = QtWidgets.QLabel("", self.infoGroup)
        self.infoLayout.addWidget(self.label_lot_info, 3, 0)
        self.infoLayout.addWidget(self.label_batchNo_info, 3, 1)
        self.label_seedlings_info = QtWidgets.QLabel("No. of Seedlings:", self.infoGroup)
        self.label_n_plants_info = QtWidgets.QLabel("", self.infoGroup)
        self.infoLayout.addWidget(self.label_seedlings_info, 4, 0)
        self.infoLayout.addWidget(self.label_n_plants_info, 4, 1)
        self.rightLayout.addWidget(self.infoGroup)
        # Table for detailed results on right
        self.resultsTable = QtWidgets.QTableView(self.rightWidget)
        self.resultsTable.setObjectName("resultsTable")
        self.rightLayout.addWidget(self.resultsTable, stretch=1)
        
        self.mainLayout.addWidget(self.rightWidget, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        
        # Menubar and statusbar with old style settings
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1321, 23))
        self.menubar.setStyleSheet("font: 63 10pt 'Segoe UI';")
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Germination Vigor Analyser"))
